# Generated by Django 5.2.8 on 2025-12-01 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_brand_product_original_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Imagen de Galería')),
                ('is_variant_swatch', models.BooleanField(default=False, verbose_name='¿Es un Swatch (Opción de color/variante)?')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product', verbose_name='Producto')),
            ],
        ),
    ]
